// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.Models;

[Table("accounts")]
[Index("Email", Name = "UQ__accounts__AB6E61642ACDFB8F", IsUnique = true)]
public partial class Account
{
    [Key]
    [Column("account_id")]
    public int AccountId { get; set; }

    [Required]
    [Column("account_name")]
    [StringLength(100)]
    [Unicode(false)]
    public string AccountName { get; set; }

    [Required]
    [Column("email")]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("password")]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("role_id")]
    public int? RoleId { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [ForeignKey("RoleId")]
    [InverseProperty("Accounts")]
    public virtual Role Role { get; set; }
}