// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.Models;

[Table("categories")]
public partial class Category
{
    [Key]
    [Column("category_id")]
    public int CategoryId { get; set; }

    [Required]
    [Column("category_name")]
    [StringLength(50)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Orchid> Orchids { get; set; } = new List<Orchid>();
}