// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.Models;

[Table("orchids")]
public partial class Orchid
{
    [Key]
    [Column("orchid_id")]
    public int OrchidId { get; set; }

    [Column("is_natural")]
    public bool IsNatural { get; set; }

    [Column("orchid_description")]
    [StringLength(255)]
    [Unicode(false)]
    public string OrchidDescription { get; set; }

    [Required]
    [Column("orchid_name")]
    [StringLength(100)]
    [Unicode(false)]
    public string OrchidName { get; set; }

    [Column("orchid_url")]
    [StringLength(255)]
    [Unicode(false)]
    public string OrchidUrl { get; set; }

    [Column("price", TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    [Column("category_id")]
    public int? CategoryId { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Orchids")]
    public virtual Category Category { get; set; }

    [InverseProperty("Orchid")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}